### ISSUE TITLE
Manual, how to build IOS application

### ISSUE THREAD

**Issue by cypherkitty** [meta-secret/meta-secret-mobile#42]
Please add documentation that explains step by step how to build the application, including:
 - how to import our project to xcode
 - what steps need to be done to install and setup rust, what targets need to be downloaded
 - how to build rust-swift-lib
 - where to copy the lib (into ios project) to make the project work
 - a so on

**Comment by LLIo6oH** [comment]
Instruction

https://github.com/meta-secret/meta-secret-mobile/blob/master/README.md
